### ISSUE TITLE
Logic of handling substeps

### ISSUE THREAD

**Issue by singvarr** [coding-vibe/checkout-form#14]
# Requirements
## Form sanitization
Some parts of the app are rendered conditionally. If a user changes their primary choice, related data should be removed:
- If a user changed payment method and they selected payment by card before, the app should reset data about card details.
- If a user changed delivery mode and:
   - they selected to the post office, remove their data about post office.
   - they selected to home, remove address details.

## Main menu changes
Also choice of substep should be reflected in the main menu: 
- Card details should appear as substep of the 'Payment mode' menu item if this payment method is selected
- Home address or post office should appear as a substep of the 'Address details' menu item if a corresponding option is selected
- If a user changes the payment type to 'By cash', a 'Credit card details' menu subitem should disappear
- If a user changes the delivery type, menu subitem should be updated according to the choice.

**Comment by coding-vibe** [comment]
## Navigation logic

- Implement stepper. Keep step active if a step or any its substeps are active
- Detect first incompleted step
  - If a user tries to open any other future step they should be redirected to the first incompleted step
- A user can go to any completed step or the first incompleted step:
  - Add logic for initialization of `initialValues` from context.
  - Show a modal where we ask a user to confirm that their changes will be lost:
    - if a user confirms changes, doesn't save values in the form and perform redirect
    - if a user denies changes, the modal closes.

## Context structure

- current step - `FormScreens`
- first incompleted step - `FormScreens`
- logic for verification than a user can access requested route - `(screen: FormScreens) => boolean`

## On submit

- save form values
- update current by incrementing
- compare current first incompleted step and new first incompleted step. Update value if a new first incompleted step is bigger.

```ts
type Step<T> = {
  values: T;
  order: number;
  subStep?: {
    id: FormSubSteps;
    values: object;
    isStepCompleted: boolean;
  };
  isStepCompleted: boolean;
};
```

**Comment by coding-vibe** [comment]
# Plan of implementation of form steps logic

1. Remove substeps from the stepper
2. Remove substeps from initial values and update the type in the context
3. Update the save form handler in the context
4. Add effects in the context that add/remove substeps on form submission
5. Apply the updated handler in the substeps
6. Fix `FullOrderDetails`.

**Comment by singvarr** [comment]
# Plan of HOC implementation used for form submission
1. Think about input and output of HOC.
2. Check and implement [remote form submit](https://final-form.org/docs/react-final-form/faq#how-can-i-trigger-a-submit-from-outside-my-form).
3. Add logic for retrieval of initial values.
4. Apply HOC for all form screens.
5. **Bonus** - write [HOC TypeScript signature](https://github.com/piotrwitek/react-redux-typescript-guide#higher-order-components)

**Comment by singvarr** [comment]
# Plan for TS improvements

1. Describe separate interfaces for initial and submit values of each screen. Put types for each screen in separate files
2. Remove empty fields in initial values in the context
3. Update context type - describe it using interfaces and `FormScreenValueType`.

```ts
type FormScreenValueType<SubmitFormValues, InitialFormValues = Record<string, never>> =
  | SubmitFormValues
  | InitialFormValues;
```

4. Apply new types to HOC - make HOC generic. HOC should accept `SubmitFormValues` and `InitialFormValues` as generic params and use it in the component.
5. Apply new types to each form screen.
  - Add generics to functional component
  - Create reusable interface in `src/types` that will list props injected by HOC. Interface for component props should extend this basic interface.
  - Apply generics to `Form` component from the `react-final-form`. It accepts type for values as the first generic and type for initial values as the second one.
